/**
 * config-template.ts — generates a ready-to-use config.yaml for a PlayGate host.
 *
 * Framework-free (no React). Uses the same key names as config.example.yaml.
 */

export interface HostConfigOpts {
  roomId: string;
  signalingUrl: string;
  serverUrl: string;
  apiKey: string;
  publicKeyBase64: string;
}

/**
 * Build a complete config.yaml string for a PlayGate host instance.
 * String values that may contain special YAML characters are double-quoted.
 */
export function buildHostConfig(opts: HostConfigOpts): string {
  const { roomId, signalingUrl, serverUrl, apiKey, publicKeyBase64 } = opts;

  return [
    `# Generated by PlayGate console for room ${roomId}.`,
    `# Copy to config.yaml on the host machine, then run:`,
    `#   go run ./cmd/host -config config.yaml`,
    ``,
    `# Video capture source.`,
    `# Replace source with v4l2 and add device: /dev/video0 when a capture card is attached.`,
    `capture:`,
    `  source: synthetic`,
    `  width: 1280`,
    `  height: 720`,
    `  fps: 30`,
    `  format: YUYV`,
    ``,
    `# H.264 encoder (software libx264; switch codec for hardware acceleration).`,
    `encoder:`,
    `  bitrate: 6000000`,
    `  preset: ultrafast`,
    `  keyframe_interval: 60`,
    `  ffmpeg_path: ffmpeg`,
    `  codec: libx264`,
    ``,
    `# Adaptive bitrate — disabled; encoder runs at fixed encoder.bitrate.`,
    `abr:`,
    `  enabled: false`,
    ``,
    `# Pion WebRTC peer connection.`,
    `webrtc:`,
    `  ice_servers:`,
    `    - stun:stun.l.google.com:19302`,
    ``,
    `# Controller input target.`,
    `input:`,
    `  target: nxbt`,
    `  socket_path: /run/nxbt/nxbt.sock`,
    `  rate_hz: 120`,
    ``,
    `# Single-controller session gate — enabled with the server's Ed25519 public key.`,
    `session:`,
    `  enabled: true`,
    `  public_key_base64: "${publicKeyBase64}"`,
    `  idle_timeout_seconds: 60`,
    ``,
    `# Signaling Worker connection.`,
    `signaling:`,
    `  url: ${signalingUrl}`,
    `  room_id: ${roomId}`,
    `  poll_interval_ms: 500`,
    `  use_turn: true`,
    ``,
    `# Pipeline latency reporting.`,
    `metrics:`,
    `  report_interval_seconds: 5`,
    ``,
    `# playgate-server integration — heartbeat keeps the console online/offline status current.`,
    `server:`,
    `  url: ${serverUrl}`,
    `  api_key: "${apiKey}"`,
    `  heartbeat_interval_seconds: 30`,
    ``,
  ].join("\n");
}
